

# 直型 maven package
name: Blog-App Workflow
on:
  push:
    branches: [ master ]
    paths:
      - src/**
      - .github/workflows/ci-cd.yml
jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Create Maven settings-security.xml
        run: |
          echo "<settingsSecurity>" > $HOME/.m2/settings-security.xml
          echo "  <master>${{ secrets.MAVEN_MASTER_PASSWORD }}</master>" >> $HOME/.m2/settings-security.xml
          echo "</settingsSecurity>" >> $HOME/.m2/settings-security.xml
        env:
          MAVEN_MASTER_PASSWORD: ${{ secrets.MAVEN_MASTER_PASSWORD }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy Dockerfile And Docker-Compose File to GCE
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          source: ./
          target: /home/${{ secrets.GCE_USER }}/

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Deploy To GCE
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd /home/${{ secrets.GCE_USER }} 
            docker-compose up -d

