
name: blog_app CI/CD Pipeline
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
            - name: Build with Maven
              run: mvn -B package --file pom.xml
    deploy:
        runs-on: ubuntu-20.04
        needs: build
        steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Copy docker-compose file
            uses: appleboy/scp-action@master
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                source: "../docker-compose.yaml"
                target: "~/deploy/docker-compose.yaml"

          - name: Deploy to AWS EC2
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                    cd ~ /deploy
                    docker-compose down 
                    docker-compose pull
                    docker-compose up -d
