#
#
## 直型 maven package
#name: Blog-App Workflow
#on:
#  push:
#    branches: [ master ]
#    paths:
#      - src/**
#      - .github/workflows/ci-cd.yml
#env:
#  PROJECT_ID: blogapp-409806
#  REGION: asia-east1
#jobs:
#  # 進行 maven package
#  package:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: 17
#          distribution: 'adopt'
#
#      - name: Get project version and artifactId
#        id: mvn-version
#        run: |
#          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
#          echo "ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
#
#      - name: Set up the Maven dependencies caching
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#
#      - name: Build with Maven
#        run: mvn clean package
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.ARTIFACT_ID }}-${{ env.PROJECT_VERSION }}
#          path: target/${{ env.ARTIFACT_ID }}-${{ env.PROJECT_VERSION }}.jar
#
#  authorize:
#    runs-on: ubuntu-20.04
#    needs: package
#    steps:
#      - name: Authorize GCP
#        uses: google-github-actions/auth@v3
#        with:
#          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#
#      - name: Set up Cloud SDK
#        uses: google-github-actions/setup-gcloud@v3
#        with:
#          project_id: blogapp-409806
#          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#          export_default_credentials: true
#
#  # 進行 docker image build
#  build-image:
#    runs-on: ubuntu-20.04
#    needs: package
#    steps:
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to GCR
#        uses: docker/login-action@v3
#        with:
#          registry: asia-east1-docker.pkg.dev
#          username: ${{ secrets.GCP_USERNAME }}
#          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: asia-east1-docker.pkg.dev/blogapp-409806/blog/${{ env.ARTIFACT_ID }}:${{ env.PROJECT_VERSION }}
#
